In [2]:
import pandas as pd
import seaborn as sns

In [26]:
df = pd.read_csv("relational-test-script.csv")

control_flow = df[
    (df['filename'] == 'block.wast') |
    (df['filename'] == 'br.wast') |
    (df['filename'] == 'br_if.wast') |
    (df['filename'] == 'br_table.wast') |
    (df['filename'] == 'if.wast') |
    (df['filename'] == 'labels.wast') |
    (df['filename'] == 'left-to-right.wast') |
    (df['filename'] == 'nop.wast') |
    (df['filename'] == 'return.wast') |
    (df['filename'] == 'switch.wast') |
    (df['filename'] == 'unreachable.wast') |
    (df['filename'] == 'unreached-invalid_wasm2_compatible.wast')
]
control_flow.insert(1, 'category', 'Control Flow')

conversions = df[
    (df['filename'] == 'conversions.wast')
]
conversions.insert(1, 'category', 'Conversions')

floats = df[
    (df['filename'] == 'const.wast') |
    (df['filename'] == 'f32.wast') |
    (df['filename'] == 'f32_bitwise.wast') |
    (df['filename'] == 'f32_cmp.wast') |
    (df['filename'] == 'f64.wast') |
    (df['filename'] == 'f64_bitwise.wast') |
    (df['filename'] == 'f64_cmp.wast') |
    (df['filename'] == 'float_exprs.wast') |
    (df['filename'] == 'float_literals.wast') |
    (df['filename'] == 'float_memory.wast') |
    (df['filename'] == 'float_misc.wast')
]
floats.insert(1, 'category', 'Floats')

functions = df[
    (df['filename'] == 'call.wast') |
    (df['filename'] == 'call_indirect.wast') |
    (df['filename'] == 'elem.wast') |
    (df['filename'] == 'fac.wast') |
    (df['filename'] == 'forward.wast') |
    (df['filename'] == 'func.wast') |
    (df['filename'] == 'func_ptrs.wast') |
    (df['filename'] == 'skip-stack-guard-page.wast') |
    (df['filename'] == 'stack.wast') |
    (df['filename'] == 'table_wasm2_compatible.wast')
]
functions.insert(1, 'category', 'Functions')

global_vars = df[
    (df['filename'] == 'global.wast')
]
global_vars.insert(1, 'category', 'Global Vars.')

integers = df[
    (df['filename'] == 'i32.wast') |
    (df['filename'] == 'i64.wast') |
    (df['filename'] == 'int_exprs.wast') |
    (df['filename'] == 'int_literals.wast') |
    (df['filename'] == 'traps.wast')
]
integers.insert(1, 'category', 'Integers')

local_vars = df[
    (df['filename'] == 'local_get.wast') |
    (df['filename'] == 'local_set.wast') |
    (df['filename'] == 'local_tee.wast')
]
local_vars.insert(1, 'category', 'Local Vars.')

memory = df[
    (df['filename'] == 'address.wast') |
    (df['filename'] == 'align.wast') |
    (df['filename'] == 'data.wast') | 
    (df['filename'] == 'endianness.wast') |
    (df['filename'] == 'load.wast') | 
    (df['filename'] == 'store.wast') | 
    (df['filename'] == 'memory.wast') | 
    (df['filename'] == 'memory_grow.wast') | 
    (df['filename'] == 'memory_redundancy.wast') | 
    (df['filename'] == 'memory_size.wast') | 
    (df['filename'] == 'memory_trap.wast')
]
memory.insert(1, 'category', 'Memory')

modules = df[
    (df['filename'] == 'binary-leb128.wast') |
    (df['filename'] == 'comments.wast') |
    (df['filename'] == 'custom.wast') |
    (df['filename'] == 'exports.wast') |
    (df['filename'] == 'imports_wasm2_compatible.wast') |
    (df['filename'] == 'inline-module.wast') |
    (df['filename'] == 'linking.wast') |
    (df['filename'] == 'names.wast') |
    (df['filename'] == 'start.wast') |
    (df['filename'] == 'token.wast') |
    (df['filename'] == 'type.wast') |
    (df['filename'] == 'utf8-custom-section-id.wast') |
    (df['filename'] == 'utf8-import-field.wast') |
    (df['filename'] == 'utf8-import-module.wast') |
    (df['filename'] == 'utf8-invalid-encoding.wast')
]
modules.insert(1, 'category', 'Modules')

stack = df[
    (df['filename'] == 'select.wast') |
    (df['filename'] == 'unwind.wast')
]
stack.insert(1, 'category', 'Stack')

data = pd.concat([control_flow, conversions, floats, functions, global_vars, integers, local_vars, memory, modules, stack])

display(data)

test_files = data[data['abstract_domain'] == 'Box'].groupby(by=['category'])['filename'].size()
assertions = data[data['abstract_domain'] == 'Box'].groupby(by=['category'])['test_cases'].sum()
polyhedra = data[data['abstract_domain'] == 'Polka'].groupby(by=['category'])['passed_cases'].sum()
octagon = data[data['abstract_domain'] == 'Octagon'].groupby(by=['category'])['passed_cases'].sum()
intervals = data[data['abstract_domain'] == 'Box'].groupby(by=['category'])['passed_cases'].sum()

pd.options.display.float_format = '{:,.2f}%'.format
display(pd.DataFrame({
    'Assertions': assertions,
    'Polyhedra': polyhedra / assertions * 100,
    'Octagon': octagon / assertions * 100,
    'Intervals': intervals / assertions * 100
}))

display(pd.DataFrame({
    'Assertions': [assertions.sum()],
    'Polyhedra': [polyhedra.sum() / assertions.sum() * 100],
    'Octagon': [octagon.sum() / assertions.sum() * 100],
    'Intervals': [intervals.sum() / assertions.sum() * 100]
}))


display(assertions.sum() - octagon.sum())
display((assertions.sum() - octagon.sum()) / assertions.sum() * 100)

,filename,category,abstract_domain,passed_cases,test_cases,percent_passed,constrained_instructions,total_instructions,percent_constrained
3,block.wast,Control Flow,Polka,52,52,100.00%,394,396,99.50%
4,br.wast,Control Flow,Polka,76,76,100.00%,266,266,100.00%
5,br_if.wast,Control Flow,Polka,88,88,100.00%,390,390,100.00%
6,br_table.wast,Control Flow,Polka,138,138,100.00%,437,437,100.00%
34,if.wast,Control Flow,Polka,123,123,100.00%,553,564,98.00%
...,...,...,...,...,...,...,...,...,...
66,unwind.wast,Stack,Polka,49,49,100.00%,242,242,100.00%
125,select.wast,Stack,Octagon,0,1,0.00%,10,10,100.00%
137,unwind.wast,Stack,Octagon,49,49,100.00%,242,242,100.00%
196,select.wast,Stack,Box,94,94,100.00%,269,269,100.00%
208,unwind.wast,Stack,Box,49,49,100.00%,242,242,100.00%

              Assertions  Polyhedra  Octagon  Intervals
category
Control Flow         832    100.00%   41.35%    100.00%
Conversions          593    100.00%  100.00%    100.00%
Floats             12197     99.97%   99.97%    100.00%
Functions            339    100.00%   52.51%    100.00%
Global Vars.          48    100.00%    0.00%    100.00%
Integers             909    100.00%  100.00%    100.00%
Local Vars.           93    100.00%  100.00%    100.00%
Memory               757    100.00%   96.57%    100.00%
Modules              606    100.00%   83.99%    100.00%
Stack                143    100.00%   34.27%    100.00%

   Assertions  Polyhedra  Octagon  Intervals
0       16517     99.98%   94.44%    100.00%

918

5.557910032088151