In [11]:
import subprocess
import pandas
import io

pandas.options.mode.copy_on_write = True

result = subprocess.run(["cloc", "--include-lang=Scala", "--by-file", "--csv", "../"], capture_output=True)
cloc = pandas.read_csv(io.BytesIO(result.stdout))
cloc = cloc[["filename", "code"]]
cloc.drop(cloc.tail(1).index, inplace=True)

cloc

                                              filename  code
0    ../sturdy-core/src/main/scala/sturdy/values/in...   990
1    ../sturdy-wasm/src/main/scala/sturdy/language/...   640
2    ../sturdy-core/src/main/scala/sturdy/values/in...   561
3    ../sturdy-core/src/test/scala/sturdy/values/in...   516
4    ../sturdy-core/src/test/scala/sturdy/control/T...   421
..                                                 ...   ...
373  ../sturdy-tip/src/test/scala/sturdy/language/t...     0
374  ../sturdy-tip/src/test/scala/sturdy/language/t...     0
375  ../sturdy-tip/src/test/scala/sturdy/language/t...     0
376  ../sturdy-wasm-benchmarks/src/main/scala/sturd...     0
377  ../sturdy-wasm/src/main/scala/sturdy/language/...     0

[378 rows x 2 columns]

In [33]:
res1 = cloc[
    cloc.filename.str.contains('sturdy-wasm/src/main/.*/generic/', regex= True, na=False) |
    cloc.filename.str.contains('sturdy-wasm/src/main/.*/Interpreter.scala', regex= True, na=False) |
    cloc.filename.str.contains('sturdy-wasm/src/main/.*/ExceptionByTarget.scala', regex= True, na=False)
]
res1["language-independent"] = False
res1["reuse"] = True

res2 = cloc[
    cloc.filename.str.contains('sturdy-apron/src/main', regex= True, na=False) |
    cloc.filename.str.contains('sturdy-core/src/main/.*/RecencyAddr', regex= True, na=False) |
    cloc.filename.str.contains('sturdy-core/src/main/.*/RecencyStore', regex= True, na=False)
]
res2["language-independent"] = True
res2["reuse"] = False

res3 = cloc[
    cloc.filename.str.contains('sturdy-wasm/src/main/.*/analyses/RelationalAnalysis.scala', regex= True, na=False) |
    cloc.filename.str.contains('sturdy-wasm/src/main/.*/abstractions/Relational.*', regex= True, na=False)
]
res3["language-independent"] = False
res3["reuse"] = False

pandas.concat([res1, res2, res3])

,filename,code,language-independent,reuse
1,../sturdy-wasm/src/main/scala/sturdy/language/...,640,False,True
25,../sturdy-wasm/src/main/scala/sturdy/language/...,236,False,True
27,../sturdy-wasm/src/main/scala/sturdy/language/...,232,False,True
52,../sturdy-wasm/src/main/scala/sturdy/language/...,150,False,True
164,../sturdy-wasm/src/main/scala/sturdy/language/...,57,False,True
176,../sturdy-wasm/src/main/scala/sturdy/language/...,52,False,True
275,../sturdy-wasm/src/main/scala/sturdy/language/...,19,False,True
283,../sturdy-wasm/src/main/scala/sturdy/language/...,18,False,True
324,../sturdy-wasm/src/main/scala/sturdy/language/...,10,False,True
359,../sturdy-wasm/src/main/scala/sturdy/language/...,3,False,True
5,../sturdy-core/src/main/scala/sturdy/values/re...,378,True,False
9,../sturdy-apron/src/main/scala/sturdy/values/i...,313,True,False
11,../sturdy-apron/src/main/scala/sturdy/values/f...,307,True,False
12,../sturdy-apron/src/main/scala/sturdy/apron/Ap...,304,True,False
16,../sturdy-apron/src/main/scala/sturdy/apron/Ap...,278,True,False
17,../sturdy-apron/src/main/scala/sturdy/effect/s...,277,True,False
22,../sturdy-apron/src/main/scala/sturdy/values/c...,256,True,False
37,../sturdy-core/src/main/scala/sturdy/effect/st...,190,True,False
53,../sturdy-apron/src/main/scala/sturdy/effect/c...,148,True,False
66,../sturdy-apron/src/main/scala/sturdy/effect/b...,135,True,False
73,../sturdy-apron/src/main/scala/sturdy/apron/Fl...,122,True,False
80,../sturdy-apron/src/main/scala/sturdy/apron/Ap...,111,True,False
119,../sturdy-apron/src/main/scala/sturdy/apron/Ap...,76,True,False
122,../sturdy-apron/src/main/scala/sturdy/apron/Ap...,74,True,False
123,../sturdy-apron/src/main/scala/sturdy/apron/Ap...,74,True,False
146,../sturdy-apron/src/main/scala/sturdy/effect/s...,62,True,False
148,../sturdy-apron/src/main/scala/sturdy/effect/s...,61,True,False
152,../sturdy-apron/src/main/scala/sturdy/effect/s...,60,True,False
199,../sturdy-apron/src/main/scala/sturdy/values/o...,42,True,False
216,../sturdy-apron/src/main/scala/sturdy/values/b...,36,True,False
228,../sturdy-apron/src/main/scala/sturdy/values/b...,31,True,False
276,../sturdy-apron/src/main/scala/sturdy/apron/Re...,18,True,False
295,../sturdy-apron/src/main/scala/sturdy/apron/Ap...,14,True,False
8,../sturdy-wasm/src/main/scala/sturdy/language/...,341,False,False
88,../sturdy-wasm/src/main/scala/sturdy/language/...,99,False,False
103,../sturdy-wasm/src/main/scala/sturdy/language/...,88,False,False
139,../sturdy-wasm/src/main/scala/sturdy/language/...,65,False,False